// <auto-generated />
using System;
using BlazorApp50.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp50.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20210116011217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BlazorApp50.Data.WeatherReport", b =>
                {
                    b.Property<Guid>("WeatherReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DewPointF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TemperatureF")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WindDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WindSpeedMPH")
                        .HasColumnType("int");

                    b.HasKey("WeatherReportId");

                    b.ToTable("WeatherReports");
                });
#pragma warning restore 612, 618
        }
    }
}
